"use client"
import Link from 'next/link';
import { Inter } from 'next/font/google';
import { usePathname } from 'next/navigation';
import Head from 'next/head'; // Import next/head

const inter = Inter({ subsets: ['latin'] });

export const generateMetadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// Define or import Lectures_All as an array
const Lectures_All = ["Lecture1", "Lecture1"];

export default function RootLayout({ children }) {
  const pathname = usePathname();

  return (
    <html lang="en">
      <Head>
        <title>{generateMetadata.title}</title> {/* Set the title using next/head */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,600;0,800;1,400&family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700;1,800&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
